---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[berkshelf-api]
- name: nginx-proxy
  run_list:
  - recipe[nginx]
  - recipe[berkshelf-api]
  attributes:
    berkshelf-api:
      proxy:
        hostname: localhost
- name: apache-proxy
  run_list:
  - recipe[apache2]
  - recipe[berkshelf-api]
  attributes:
    berkshelf-api:
      proxy:
        hostname: localhost
- name: nginx-https-proxy
  run_list:
  - recipe[nginx]
  - recipe[berkshelf-api_test::certificate]
  - recipe[berkshelf-api]
  attributes:
    berkshelf-api:
      proxy:
        hostname: localhost
        ssl_enabled: true
- name: apache-https-proxy
  run_list:
  - recipe[apache2]
  - recipe[berkshelf-api_test::certificate]
  - recipe[berkshelf-api]
  attributes:
    berkshelf-api:
      proxy:
        hostname: localhost
        ssl_enabled: true
- name: gem-install
  run_list:
  - recipe[berkshelf-api]
  attributes:
    berkshelf-api:
      version: 1.1.0
